name = "Walker2020Sampling"
uuid = "f34fe3fd-af96-4859-b26f-d1ad3ec20571"
authors = ["Iván Gutiérrez <ivangutierrez1988@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.6"
